@echo off
color a
Title Are Your Ready ?
echo If You Are Ready Tape On Your Keyboard.
PAUSE
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
cd "C:\WINDOWS\system32\"
echo You Don't Crash ? You have a good pc enjoy the part 2
Title Part 2
PAUSE
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
start Taskmgr.exe
cd "C:\Program Files (x86)\Microsoft\Edge\Application"
echo Okay It's The Final Round Are You Ready ?
PAUSE
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
start msedge.exe
color f
echo Gg Your Pc Don't Crash But... Yes Gg You Win
PAUSE
color 4
echo Sorry..
PAUSE
color f
echo I'm so sad. Yes is the most devil or... not.
echo If you want to quit just do ALT+F4
cd "C:\Program Files\Google\Chrome\Application"
color f
echo No You Don't Want. Good Luck.
color 4
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
start chrome.exe
color f
echo Gg But.....
color f
echo If Your Want To Know Your Windows Version Continue
cd "C:\Windows\System32"
echo Okay... Let's go.
PAUSE
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe
start winver.exe